import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
fs.mkdirSync('dist/client',{recursive:true});
fs.writeFileSync('dist/client/obsolete-audit.txt','stale build fixture');
execFileSync(process.execPath,['scripts/build.mjs']);
assert.ok(!fs.existsSync('dist/client/obsolete-audit.txt'),'build removes obsolete output');
test('public routes and scripts exist; build excludes local data',()=>{for(const name of ['index','about','dresses','dress-lian','designers','collections','booking','contact','admin'])assert.ok(fs.readFileSync('public/'+name+'.html','utf8').includes('lang="ar"'));for(const file of ['main.js','admin.js','site-cms.js','dress-viewer.js','scene.js'])execFileSync(process.execPath,['--check',path.join('public',file)]);assert.ok(fs.existsSync('dist/server/index.js'));assert.ok(fs.existsSync('dist/client/admin.html'));assert.ok(fs.existsSync('dist/.openai/drizzle/meta/_journal.json'));assert.ok(!fs.existsSync('dist/client/.local'));assert.ok(!fs.readFileSync('dist/server/index.js','utf8').includes('owner@local.test'));});
test('dress enquiry button targets the Golden Lines WhatsApp number',()=>{const source=fs.readFileSync('public/site-cms.js','utf8');assert.ok(source.includes('https://wa.me/966582620880?text='));assert.ok(source.includes('رمز التصميم'))});
