import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker,{validateData} from '../server/worker.mjs';
import seed from '../server/seed.json' with {type:'json'};
function setup(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const DB={prepare(query){return {bind(...values){return {async first(){return sql.prepare(query).get(...values)||null},async all(){return {results:sql.prepare(query).all(...values)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}}}}}}}};const files=new Map();const env={DB,ADMIN_OWNER_EMAIL:'owner@example.test',BUCKET:{async put(id,bytes,opt){files.set(id,{body:bytes,httpMetadata:opt.httpMetadata})},async get(id){return files.get(id)},async delete(id){files.delete(id)}},ASSETS:{fetch:()=>new Response('asset')}};return {env,sql,files};}
function request(path,method='GET',data=null,role='owner',extra={}){return new Request('https://shop.test'+path,{method,headers:{Origin:'https://shop.test',...(role?{'oai-authenticated-user-id':role+'-id','oai-authenticated-user-email':role+'@example.test'}:{}),...(data?{'Content-Type':'application/json'}:{}),...extra},...(data?{body:JSON.stringify(data)}:{})})}
async function call(env,...args){const r=await worker.fetch(request(...args),env);return {status:r.status,body:await r.json()}}
const booking={name:'عميلة اختبار',phone:'0501234567',date:'2027-01-02',wedding:'2027-02-01',time:'10:00',service:'تجربة فستان',dress:'lian',notes:''};
test('anonymous, unknown and cross-origin callers cannot administer',async()=>{const {env}=setup();assert.equal((await call(env,'/api/admin/content','GET',null,null)).status,401);assert.equal((await call(env,'/api/admin/content','GET',null,'stranger')).status,403);assert.equal((await call(env,'/api/admin/content','PUT',{data:seed,revision:0},'owner',{Origin:'https://evil.test'})).status,403);assert.equal((await call(env,'/api/admin/content')).status,200)});
test('content persists, stale edits rejected, unpublished designs excluded',async()=>{const {env}=setup(),d=structuredClone(seed);d.dresses[0].published=false;let r=await call(env,'/api/admin/content','PUT',{data:d,revision:0});assert.equal(r.status,200);assert.equal(r.body.revision,1);assert.equal((await call(env,'/api/admin/content','PUT',{data:seed,revision:0})).status,409);const pub=await call(env,'/api/catalog','GET',null,null);assert.equal(pub.body.data.dresses.length,7);assert.equal((await call(env,'/api/admin/content')).body.data.dresses.length,8)});
test('data validation rejects unsafe files, bad angles, missing relationships',()=>{for(const mutate of [d=>d.settings.logo='javascript:alert(1)',d=>d.dresses[0].frames[1].angle=0,d=>d.dresses[0].group='unknown',d=>d.settings.openTime=24,d=>d.settings.instagram='javascript:alert(1)']){const d=structuredClone(seed);mutate(d);assert.throws(()=>validateData(d))}assert.equal(validateData(structuredClone(seed)).dresses.length,8)});
test('booking requests persist idempotently and capacity is enforced atomically',async()=>{const {env}=setup();const key=crypto.randomUUID();const send=()=>call(env,'/api/bookings','POST',booking,null,{'Idempotency-Key':key});const first=await send();assert.equal(first.status,201);assert.equal((await send()).body.id,first.body.id);const second=await call(env,'/api/bookings','POST',{...booking,name:'عميلة ثانية'},null,{'Idempotency-Key':crypto.randomUUID()});assert.equal(second.status,201);assert.equal((await call(env,'/api/admin/requests/'+first.body.id,'PATCH',{status:'confirmed',version:1,notes:'تم التنسيق'})).status,200);assert.equal((await call(env,'/api/admin/requests/'+second.body.id,'PATCH',{status:'confirmed',version:1,notes:''})).status,409);assert.equal((await call(env,'/api/admin/requests/'+first.body.id,'PATCH',{status:'completed',version:1,notes:''})).status,409);assert.equal((await call(env,'/api/admin/requests')).body.length,2)});
test('closure, invalid inputs, messages, newsletter and rate limits',async()=>{const {env}=setup();assert.equal((await call(env,'/api/bookings','POST',{...booking,date:'2027-01-01'},null,{'Idempotency-Key':crypto.randomUUID()})).status,400);assert.equal((await call(env,'/api/messages','POST',{name:'اختبار',email:'bad',subject:'سؤال',message:'مرحبًا'},null,{'Idempotency-Key':crypto.randomUUID()})).status,400);assert.equal((await call(env,'/api/messages','POST',{name:'اختبار',email:'test@example.test',subject:'سؤال',message:'مرحبًا'},null,{'Idempotency-Key':crypto.randomUUID()})).status,201);assert.equal((await call(env,'/api/subscribers','POST',{email:'test@example.test'},null,{'Idempotency-Key':crypto.randomUUID()})).status,201);let r;for(let i=0;i<20;i++)r=await call(env,'/api/subscribers','POST',{email:'test@example.test'},null,{'Idempotency-Key':crypto.randomUUID()});assert.equal(r.status,429)});
test('team roles separated; owner cannot be removed; revoked member blocked',async()=>{const {env}=setup();assert.equal((await call(env,'/api/admin/members','POST',{name:'Editor',email:'editor@example.test',role:'editor'})).status,200);assert.equal((await call(env,'/api/admin/content','GET',null,'editor')).status,200);assert.equal((await call(env,'/api/admin/requests','GET',null,'editor')).status,403);assert.equal((await call(env,'/api/admin/members','GET',null,'editor')).status,403);assert.equal((await call(env,'/api/admin/members/owner%40example.test','DELETE')).status,400);await call(env,'/api/admin/members/editor%40example.test','DELETE');assert.equal((await call(env,'/api/admin/content','GET',null,'editor')).status,403)});
test('media upload validates signature, stores bytes, protects referenced images',async()=>{const {env}=setup();await call(env,'/api/admin/me');const upload=async(file)=>{const f=new FormData();f.append('file',file);return worker.fetch(new Request('https://shop.test/api/admin/media',{method:'POST',headers:{Origin:'https://shop.test','oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.test'},body:f}),env)};assert.equal((await upload(new File(['<svg/>'],'evil.jpg',{type:'image/jpeg'}))).status,400);const r=await upload(new File([new Uint8Array([255,216,255,224,0,0,0,0])],'test.jpg',{type:'image/jpeg'}));assert.equal(r.status,201);const item=await r.json();const d=structuredClone(seed);d.dresses[0].image=item.url;await call(env,'/api/admin/content','PUT',{data:d,revision:0});assert.equal((await call(env,'/api/admin/media/'+item.id,'DELETE')).status,409);await call(env,'/api/admin/content','PUT',{data:seed,revision:1});assert.equal((await call(env,'/api/admin/media/'+item.id,'DELETE')).status,200)});

